# -*- coding: utf-8 -*-
"""Car_poly.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rIMTeNqT_tiG20g4Vr9DB9grttL5kswo
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/content/car economy price.csv")
df

df.head

df.tail

df.columns

df.shape

df.isna().sum()

df.drop(['Unnamed: 0'],axis=1,inplace=True)
df

df.dtypes

df['Name'].value_counts()

df['Location'].value_counts()

import seaborn as sns
sns.countplot(x=df['Location'],color='red')

df['Fuel_Type'].value_counts()

sns.countplot(x=df['Fuel_Type'],color='orange')

df['Transmission'].value_counts()

sns.countplot(x=df['Transmission'],color='blue')

df['Owner_Type'].value_counts()

sns.countplot(x=df['Owner_Type'],color='yellow')

df.isna().sum()

dummy=pd.get_dummies(df[['Location','Fuel_Type','Transmission','Owner_Type',]],drop_first=True) #first column drop : drop_first
dummy

# concatinate old_dataframe with dummy
df1=pd.concat([df,dummy],axis=1)
df1

df1=df1.drop(['Location','Fuel_Type','Transmission','Owner_Type','New_Price','Name','Fuel_Type_Electric'],axis=1)
df1

df1.dtypes

# replace object type
df1['Mileage']=df1['Mileage'].str.replace('km/kg','')
df1['Mileage']=df1['Mileage'].str.replace('kmpl','')
df1['Mileage']=df1['Mileage'].str.replace('null','0')

df1['Engine']=df1['Engine'].str.replace('CC','')
df1['Engine']=df1['Engine'].str.replace('null','0')

df1['Power']=df1['Power'].str.replace('bhp','')
df1['Power']=df1['Power'].str.replace('null','0')
df1

df1.dtypes

df1.isna().sum()

# convert object  to float
df1['Mileage']=df1['Mileage'].astype(float)
df1['Engine']=df1['Engine'].astype(float)
df1['Power']=df1['Power'].astype(float)
df1

df1.dtypes

# convert float(0)/int(0) to NaN
df1.loc[df1.Engine==0,'Engine']=np.NaN
df1.loc[df1.Power==0,'Power']=np.NaN
df1.loc[df1.Mileage==0,'Mileage']=np.NaN
df1

df1.isna().sum()

# fill missing value with mean/mode
df1['Engine']=df1['Engine'].fillna(df1['Engine'].mean())
df1['Mileage']=df1['Mileage'].fillna(df1['Mileage'].mean())
df1['Power']=df1['Power'].fillna(df1['Power'].mean())
df1['Seats']=df1['Seats'].fillna(df1['Seats'].mode()[0])
df1

df1.isna().sum()

x=df1.drop(['Price'],axis=1)
x

y=df1['Price']
y

# TEST DATA

dft=pd.read_csv("/content/test-data.csv")
dft

dft.drop(['Unnamed: 0'],axis=1,inplace=True)
dft

dummy1=pd.get_dummies(dft[['Location','Fuel_Type','Transmission','Owner_Type',]],drop_first=True) #first column drop : drop_first
dummy1

# concatinate old_dataframe with dummy
df2=pd.concat([dft,dummy1],axis=1)
df2

df2=df2.drop(['Location','Fuel_Type','Transmission','Owner_Type','New_Price','Name'],axis=1)
df2

df2.isna().sum()

# replace object type
df2['Mileage']=df2['Mileage'].str.replace('km/kg','')
df2['Mileage']=df2['Mileage'].str.replace('kmpl','')
df2['Mileage']=df2['Mileage'].str.replace('null','0')

df2['Engine']=df2['Engine'].str.replace('CC','')
df2['Engine']=df2['Engine'].str.replace('null','0')

df2['Power']=df2['Power'].str.replace('bhp','')
df2['Power']=df2['Power'].str.replace('null','0')
df2

df2.isna().sum()

# convert object  to float
df2['Mileage']=df2['Mileage'].astype(float)
df2['Engine']=df2['Engine'].astype(float)
df2['Power']=df2['Power'].astype(float)
df2

# missing value handling
df2['Engine']=df2['Engine'].fillna(df1['Engine'].mean())
df2['Power']=df2['Power'].fillna(df1['Power'].mean())
df2['Seats']=df2['Seats'].fillna(df1['Seats'].mode()[0])
df2['Mileage']=df2['Mileage'].fillna(df1['Mileage'].mean())
df2

df2.isna().sum()

w=df2