# -*- coding: utf-8 -*-
"""dia_NB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrVVyXU7jJLQTVSkbIp4R-g617D3E0Pk
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/diabetes.csv")
df

df.shape

df.describe()

print(df.isna().sum())

# input and output

x=df.iloc[:,:-1].values
x

y=df.iloc[:,-1].values
y

# model selection

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

x_test

y_train

y_test

# pre-processing
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
scaler.fit(x_test)

x_train=scaler.transform(x_train)
x_train

x_test=scaler.transform(x_test)
x_test

# model  creation
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
y_pred

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,ConfusionMatrixDisplay
result=confusion_matrix(y_test,y_pred)
result

report=classification_report(y_test,y_pred)
report

score=accuracy_score(y_test,y_pred)
score

print(ConfusionMatrixDisplay.from_predictions(y_test,y_pred))