# -*- coding: utf-8 -*-
"""dia_SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11R170_G-Fc9B7cewPIQ6oIRBBiMzuAyS
"""

import numpy as np
import pandas as pd
df=pd.read_csv("/content/diabetes.csv")
df

# find shapes
df.shape

# to get dicription of dataset
df.describe()

# check null values
print(df.isna().sum())

# input and output
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values
x
y

# model selection

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

# pre-proceesing/transform

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)

x_train=scaler.transform(x_train)
print(x_train)

x_test=scaler.transform(x_test)
print(x_test)

# model creation
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(x_train,y_train)

y_pred=classifier.predict(x_test)
print(y_pred)

# accuracy

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,ConfusionMatrixDisplay
result=confusion_matrix(y_pred,y_test)
print(result)

print(classification_report(y_test,y_pred))

score=accuracy_score(y_pred,y_test)
print(score)